{
 "title": "APC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "model_name", "label": "model_name", "query": { "query": "label_values(model_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apc_exporter_status{model_name=\"$model_name\"}",
     "legendFormat": "Current battery voltage"
    }
   ]
  },
  {
   "title": "Time Remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apc_exporter_remaining_runtime{model_name=\"$model_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "apc_exporter_load_pct{model_name=\"$model_name\"}",
     "legendFormat": "Load %"
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "apc_exporter_bcharge{model_name=\"$model_name\"}",
     "legendFormat": "Battery Capacity"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "apc_exporter_battv{model_name=\"$model_name\"}",
     "legendFormat": "Current battery voltage"
    }
   ]
  },
  {
   "title": "Line voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "apc_exporter_linev{model_name=\"$model_name\"}",
     "legendFormat": "Current input line voltage"
    }
   ]
  }
 ]
}